[package]
name = "libdnssd"
version = "0.1.0"
edition = "2021"
authors = ["Mikael Sahlström <mick.sahlstrom@gmail.com>"]

[dependencies]
socket2 = { version = "0.5.4", features = ["all"] }
lazy_static = "1.4.0"
clap = { version = "4.4.6", features = ["derive"] }
ansi_term = "0.12.1"
default-net = "0.17.0"
